spring:
  datasource:
    url: jdbc:postgresql://database-1.cz549sqq9eyc.eu-west-1.rds.amazonaws.com/glamorous
    username: postgres
    password: d8%Ot2Ds2WO!

spring.jpa.hibernate.ddl-auto: update
spring.jpa.database: postgresql